consumes:
- application/json
definitions:
  CreateNewUserRequest:
    properties:
      Name:
        type: string
        uniqueItems: true
      Password:
        type: string
    required:
    - Name
    - Password
    type: object
    x-go-package: github.com/panytsch/microservice-poc-db/go/rest_v1
  CreateNewUserResponse:
    properties:
      ID:
        format: uint64
        type: integer
      Name:
        type: string
    type: object
    x-go-package: github.com/panytsch/microservice-poc-db/go/rest_v1
  ErrorCode:
    format: uint16
    type: integer
    x-go-package: github.com/panytsch/microservice-poc-db/go/rest_v1
  ErrorResponse:
    properties:
      Code:
        $ref: '#/definitions/ErrorCode'
      Message:
        description: Error description
        type: string
    type: object
    x-go-package: github.com/panytsch/microservice-poc-db/go/rest_v1
  GetTransactionResponse:
    properties:
      Amount:
        $ref: '#/definitions/TransactionAmount'
      ID:
        format: uint64
        type: integer
      Status:
        $ref: '#/definitions/TransactionStatus'
    type: object
    x-go-package: github.com/panytsch/microservice-poc-db/go/rest_v1
  GetTransactionsResponse:
    properties:
      Amount:
        $ref: '#/definitions/TransactionAmount'
      ID:
        format: uint64
        type: integer
      Status:
        $ref: '#/definitions/TransactionStatus'
    type: object
    x-go-package: github.com/panytsch/microservice-poc-db/go/rest_v1
  GetUserRequest:
    properties:
      Name:
        type: string
      Password:
        type: string
    required:
    - Name
    - Password
    type: object
    x-go-package: github.com/panytsch/microservice-poc-db/go/rest_v1
  MakeTransactionRequest:
    properties:
      Amount:
        $ref: '#/definitions/TransactionAmount'
    required:
    - Amount
    type: object
    x-go-package: github.com/panytsch/microservice-poc-db/go/rest_v1
  MakeTransactionResponse:
    properties:
      Amount:
        $ref: '#/definitions/TransactionAmount'
      ID:
        format: uint64
        type: integer
      Status:
        $ref: '#/definitions/TransactionStatus'
    type: object
    x-go-package: github.com/panytsch/microservice-poc-db/go/rest_v1
  NoDataFoundResponse:
    properties:
      Code:
        $ref: '#/definitions/ErrorCode'
      Message:
        description: Error description
        type: string
    type: object
    x-go-package: github.com/panytsch/microservice-poc-db/go/rest_v1
  TransactionAmount:
    format: int64
    type: integer
    x-go-package: github.com/panytsch/microservice-poc-db/go/pkg/db
  TransactionStatus:
    description: 1 - created
    format: int64
    type: integer
    x-go-package: github.com/panytsch/microservice-poc-db/go/pkg/db
info:
  contact:
    email: gfyroman@gmail.com
    name: Roman Panasiuk
  description: |-
    the purpose of this application is to provide an application
    to work with DB like with service
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
  title: DB microservice REST API.
  version: 1.0.0
paths:
  /rest/v1//users/get:
    post:
      description: Get user
      operationId: getUser
      parameters:
      - in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/GetUserRequest'
      responses:
        "200":
          $ref: '#/responses/getUser'
        "400":
          $ref: '#/responses/errorResponse'
      tags:
      - user
  /rest/v1/transactions:
    get:
      description: Get few Transaction
      operationId: getTransactions
      parameters:
      - description: User token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          $ref: '#/responses/getTransactions'
        "400":
          $ref: '#/responses/errorResponse'
        "401":
          $ref: '#/responses/errorResponse'
      tags:
      - transaction
    post:
      description: Create new Transaction
      operationId: createTransaction
      parameters:
      - description: User token
        in: header
        name: Authorization
        type: string
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/MakeTransactionRequest'
      responses:
        "201":
          $ref: '#/responses/createTransaction'
        "400":
          $ref: '#/responses/errorResponse'
        "401":
          $ref: '#/responses/errorResponse'
      tags:
      - transaction
  /rest/v1/transactions/{TransactionID}:
    get:
      description: Get one Transaction
      operationId: getTransaction
      parameters:
      - description: User token
        in: header
        name: Authorization
        required: true
        type: string
      - format: uint64
        in: path
        name: TransactionID
        required: true
        type: integer
      responses:
        "200":
          $ref: '#/responses/getTransaction'
        "400":
          $ref: '#/responses/errorResponse'
        "401":
          $ref: '#/responses/errorResponse'
      tags:
      - transaction
  /rest/v1/users:
    post:
      description: Create new user
      operationId: createUser
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/CreateNewUserRequest'
      responses:
        "201":
          $ref: '#/responses/createUser'
        "400":
          $ref: '#/responses/errorResponse'
      tags:
      - user
produces:
- application/json
responses:
  createTransaction:
    schema:
      $ref: '#/definitions/MakeTransactionResponse'
  createUser:
    schema:
      $ref: '#/definitions/CreateNewUserResponse'
  errorResponse:
    schema:
      $ref: '#/definitions/ErrorResponse'
  getTransaction:
    schema:
      $ref: '#/definitions/GetTransactionResponse'
  getTransactions:
    schema:
      items:
        $ref: '#/definitions/GetTransactionsResponse'
      type: array
  getUser:
    schema:
      $ref: '#/definitions/CreateNewUserResponse'
  noDataFound:
    schema:
      $ref: '#/definitions/NoDataFoundResponse'
schemes:
- http
swagger: "2.0"
