consumes:
- application/json
definitions:
  CreateNewUserRequest:
    properties:
      Name:
        type: string
        uniqueItems: true
      Password:
        type: string
    required:
    - Name
    - Password
    type: object
    x-go-package: github.com/panytsch/microservice-poc-db/go/rest_v1
  CreateNewUserResponse:
    properties:
      ID:
        format: uint64
        type: integer
      Name:
        type: string
    type: object
    x-go-package: github.com/panytsch/microservice-poc-db/go/rest_v1
  ErrorCode:
    format: uint16
    type: integer
    x-go-package: github.com/panytsch/microservice-poc-db/go/rest_v1
  ErrorResponse:
    properties:
      Code:
        $ref: '#/definitions/ErrorCode'
      Message:
        description: Error description
        type: string
    type: object
    x-go-package: github.com/panytsch/microservice-poc-db/go/rest_v1
  GetPaymentResponse:
    properties:
      Amount:
        $ref: '#/definitions/PaymentAmount'
      ID:
        format: uint64
        type: integer
      Status:
        $ref: '#/definitions/PaymentStatus'
    type: object
    x-go-package: github.com/panytsch/microservice-poc-db/go/rest_v1
  GetPaymentsResponse:
    properties:
      Amount:
        $ref: '#/definitions/PaymentAmount'
      ID:
        format: uint64
        type: integer
      Status:
        $ref: '#/definitions/PaymentStatus'
    type: object
    x-go-package: github.com/panytsch/microservice-poc-db/go/rest_v1
  GetRefundResponse:
    properties:
      Amount:
        $ref: '#/definitions/RefundAmount'
      ID:
        format: uint64
        type: integer
      Status:
        $ref: '#/definitions/RefundStatus'
    type: object
    x-go-package: github.com/panytsch/microservice-poc-db/go/rest_v1
  GetRefundsResponse:
    properties:
      Amount:
        $ref: '#/definitions/RefundAmount'
      ID:
        format: uint64
        type: integer
      Status:
        $ref: '#/definitions/RefundStatus'
    type: object
    x-go-package: github.com/panytsch/microservice-poc-db/go/rest_v1
  GetUserRequest:
    properties:
      Name:
        type: string
      Password:
        type: string
    required:
    - Name
    - Password
    type: object
    x-go-package: github.com/panytsch/microservice-poc-db/go/rest_v1
  GetUserResponse:
    properties:
      Balance:
        format: int64
        type: integer
      CCNumber:
        type: string
      ID:
        format: uint64
        type: integer
      Name:
        type: string
    type: object
    x-go-package: github.com/panytsch/microservice-poc-db/go/rest_v1
  MakePaymentRequest:
    properties:
      Amount:
        $ref: '#/definitions/PaymentAmount'
    required:
    - Amount
    type: object
    x-go-package: github.com/panytsch/microservice-poc-db/go/rest_v1
  MakePaymentResponse:
    properties:
      Amount:
        $ref: '#/definitions/PaymentAmount'
      ID:
        format: uint64
        type: integer
      Status:
        $ref: '#/definitions/PaymentStatus'
    type: object
    x-go-package: github.com/panytsch/microservice-poc-db/go/rest_v1
  MakeRefundRequest:
    properties:
      Amount:
        $ref: '#/definitions/RefundAmount'
    required:
    - Amount
    type: object
    x-go-package: github.com/panytsch/microservice-poc-db/go/rest_v1
  MakeRefundResponse:
    properties:
      Amount:
        $ref: '#/definitions/RefundAmount'
      ID:
        format: uint64
        type: integer
      Status:
        $ref: '#/definitions/RefundStatus'
    type: object
    x-go-package: github.com/panytsch/microservice-poc-db/go/rest_v1
  NoDataFoundResponse:
    properties:
      Code:
        $ref: '#/definitions/ErrorCode'
      Message:
        description: Error description
        type: string
    type: object
    x-go-package: github.com/panytsch/microservice-poc-db/go/rest_v1
  PaymentAmount:
    format: int64
    type: integer
    x-go-package: github.com/panytsch/microservice-poc-db/go/pkg/db
  PaymentStatus:
    description: |-
      1 PaymentStatusCreated
      2 PaymentStatusInProgress
      3 PaymentStatusInFinished
      4 PaymentStatusInCancelled
    format: int64
    type: integer
    x-go-package: github.com/panytsch/microservice-poc-db/go/pkg/db
  RefundAmount:
    format: int64
    type: integer
    x-go-package: github.com/panytsch/microservice-poc-db/go/pkg/db
  RefundStatus:
    description: |-
      1 RefundStatusCreated
      2 RefundStatusInProgress
      3 RefundStatusFinished
      4 RefundStatusCancelled
    format: int64
    type: integer
    x-go-package: github.com/panytsch/microservice-poc-db/go/pkg/db
info:
  contact:
    email: gfyroman@gmail.com
    name: Roman Panasiuk
  description: |-
    the purpose of this application is to provide an application
    to work with DB like with service
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
  title: DB microservice REST API.
  version: 1.0.0
paths:
  /rest/v1//users:
    get:
      description: Get user
      operationId: getUserByToken
      parameters:
      - description: User token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          $ref: '#/responses/getUserByToken'
        "400":
          $ref: '#/responses/errorResponse'
      tags:
      - user
  /rest/v1//users/get:
    post:
      description: Get user
      operationId: getUser
      parameters:
      - in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/GetUserRequest'
      responses:
        "200":
          $ref: '#/responses/getUser'
        "400":
          $ref: '#/responses/errorResponse'
      tags:
      - user
  /rest/v1/Payments:
    get:
      description: Get few Payment
      operationId: getPayments
      parameters:
      - description: User token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          $ref: '#/responses/getPayments'
        "400":
          $ref: '#/responses/errorResponse'
        "401":
          $ref: '#/responses/errorResponse'
      tags:
      - Payment
    post:
      description: Create new Payment
      operationId: createPayment
      parameters:
      - description: User token
        in: header
        name: Authorization
        type: string
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/MakePaymentRequest'
      responses:
        "201":
          $ref: '#/responses/createPayment'
        "400":
          $ref: '#/responses/errorResponse'
        "401":
          $ref: '#/responses/errorResponse'
      tags:
      - Payment
  /rest/v1/Payments/{PaymentID}:
    get:
      description: Get one Payment
      operationId: getPayment
      parameters:
      - description: User token
        in: header
        name: Authorization
        required: true
        type: string
      - format: uint64
        in: path
        name: PaymentID
        required: true
        type: integer
      responses:
        "200":
          $ref: '#/responses/getPayment'
        "400":
          $ref: '#/responses/errorResponse'
        "401":
          $ref: '#/responses/errorResponse'
      tags:
      - Payment
  /rest/v1/refunds:
    get:
      description: Get few Refunds
      operationId: getRefunds
      parameters:
      - description: User token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          $ref: '#/responses/getRefunds'
        "400":
          $ref: '#/responses/errorResponse'
        "401":
          $ref: '#/responses/errorResponse'
      tags:
      - refund
    post:
      description: Create new Refund
      operationId: createRefund
      parameters:
      - description: User token
        in: header
        name: Authorization
        type: string
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/MakeRefundRequest'
      responses:
        "201":
          $ref: '#/responses/createRefund'
        "400":
          $ref: '#/responses/errorResponse'
        "401":
          $ref: '#/responses/errorResponse'
      tags:
      - refund
  /rest/v1/refunds/{RefundID}:
    get:
      description: Get one Refund
      operationId: getRefund
      parameters:
      - description: User token
        in: header
        name: Authorization
        required: true
        type: string
      - format: uint64
        in: path
        name: RefundID
        required: true
        type: integer
      responses:
        "200":
          $ref: '#/responses/getRefund'
        "400":
          $ref: '#/responses/errorResponse'
        "401":
          $ref: '#/responses/errorResponse'
      tags:
      - refund
  /rest/v1/users:
    post:
      description: Create new user
      operationId: createUser
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/CreateNewUserRequest'
      responses:
        "201":
          $ref: '#/responses/createUser'
        "400":
          $ref: '#/responses/errorResponse'
      tags:
      - user
produces:
- application/json
responses:
  createPayment:
    schema:
      $ref: '#/definitions/MakePaymentResponse'
  createRefund:
    schema:
      $ref: '#/definitions/MakeRefundResponse'
  createUser:
    schema:
      $ref: '#/definitions/CreateNewUserResponse'
  errorResponse:
    schema:
      $ref: '#/definitions/ErrorResponse'
  getPayment:
    schema:
      $ref: '#/definitions/GetPaymentResponse'
  getPayments:
    schema:
      items:
        $ref: '#/definitions/GetPaymentsResponse'
      type: array
  getRefund:
    schema:
      $ref: '#/definitions/GetRefundResponse'
  getRefunds:
    schema:
      items:
        $ref: '#/definitions/GetRefundsResponse'
      type: array
  getUser:
    schema:
      $ref: '#/definitions/GetUserResponse'
  getUserByToken:
    schema:
      $ref: '#/definitions/GetUserResponse'
  noDataFound:
    schema:
      $ref: '#/definitions/NoDataFoundResponse'
schemes:
- http
swagger: "2.0"
