version: '3.7'
services:
#  go:
#    container_name: go_with_dep
#    build: ./.docker/go
#    volumes:
#      - C:\testGit\go_poc\mssql\go:.
#      - C:\testGit\go_poc\mssql\go\.netrc:/root/.netrc
#      - C:\testGit\go_poc\mssql\go\netrc:/root/netrc
#    networks:
#      - default
#    environment:
#      - mtu=1454
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - 1433:1433
    volumes:
      - ./mssql/data/:/var/opt/mssql/data
    networks:
      - default