version: '3.7'
services:
  go:
    container_name: go_with_dep
    build: ${GO_DOCKERFILE_PATH}
    depends_on:
      - mssql
    ports:
      - 80:80
    networks:
      - default
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - 1433:1433
    volumes:
      - ./mssql/data/:/var/opt/mssql/data
    networks:
      - default