version: '3.7'
services:
  go:
    container_name: go_with_dep
    build: ${GO_DOCKERFILE_PATH}
    depends_on:
      - mssql
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - default
    env_file:
      - go/vars.env
      - shared_vars.env
    environment:
      - DB_PORT=${DB_PORT}
      - APP_PORT=${APP_PORT}
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2017-latest
    env_file:
      - mssql/vars.env
      - shared_vars.env
    environment:
      - MSSQL_TCP_PORT=${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ${DB_HOST_PATH}:${DB_CONTAINER_PATH}
    networks:
      - default